import type { Metadata } from "next";
import "@fontsource/bebas-neue";
import "@fontsource/bangers";
import "@fontsource/rajdhani";
import "./globals.css";
import FlashProvider from "@/components/FlashProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      style={{
        "--font-bebas-neue": '"Bebas Neue", sans-serif',
        "--font-bangers": '"Bangers", system-ui',
        "--font-rajdhani": '"Rajdhani", sans-serif',
      } as React.CSSProperties}
    >
      <body className="antialiased">
        <FlashProvider>
          {children}
        </FlashProvider>
      </body>
    </html>
  );
}
